# Numpy

In [443]:
import numpy as np

In [444]:
print(np.__version__)

2.0.2


## Type

### 1D : Vector

In [376]:
#---------- Define
a = np.array(
    [1, 2, 3]
)

In [377]:
print("all elements:", a)                           # Display all elements

all elements: [1 2 3]


In [378]:
print("First element:", a[0])                       # First element
print("Last element:", a[-1])                       # Last element

First element: 1
Last element: 3


In [379]:
print("Elements from index 0 to the 2:", a[0:2])    # Elements from index 0 to the 2
print("First two elements:", a[:2])                 # First two elements
print("Elements from index 2 to the end:", a[2:])   # Elements from index 2 to the end
print("All but the last two elements:", a[:-2])     # All but the last two elements
print("Last two elements:", a[-2:])                 # Last two elements

Elements from index 0 to the 2: [1 2]
First two elements: [1 2]
Elements from index 2 to the end: [3]
All but the last two elements: [1]
Last two elements: [2 3]


### 2D : Matrix

In [380]:
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

In [381]:
print("First row, first column:", a[0][0])   # First row, first column
print("First row, first column:", a[0, 0])   # First row, first column 

First row, first column: 1
First row, first column: 1


In [382]:
print("First row:", a[0])                    # First row
print("First row:", a[0, :])                 # First row
print("First column:", a[:, 0])              # First column

First row: [1 2 3]
First row: [1 2 3]
First column: [1 4 7]


### 3D : Matrix

In [383]:
a = np.array(
    [
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ],
        [
            [7, 8],
            [9, 10],
            [11, 12]
        ],
        [
            [13, 14],
            [15, 16],
            [17, 18]
        ],
        [
            [19, 20],
            [21, 22],
            [23, 24]
        ]
    ]
)

## Inspection

In [385]:
a = np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6],
    ]
)

In [386]:
print("shape:", a.shape)         # shape
print("shape:", np.shape(a))     # shape
print("len:", len(a))            # len
print("dtype:", a.dtype)         # dtype
print("item-size:", a.itemsize)  # item-size
print("size:", a.size)           # size
print("ndim:", a.ndim)           # ndim

shape: (3, 2)
shape: (3, 2)
len: 3
dtype: int64
item-size: 8
size: 6
ndim: 2


In [324]:
print("Max:", a.max())
print("Min:", a.min())
print("Sum:", a.sum())

Max: 6
Min: 1
Sum: 21


In [320]:
print("Max:", np.max(a, axis=0)) 
print("Max:", np.max(a, axis=1)) 

Max: [5 6]
Max: [2 4 6]


In [322]:
print("Min:", np.min(a, axis=0)) 
print("Min:", np.min(a, axis=1)) 

Min: [1 2]
Min: [1 3 5]


In [321]:
print("Sum:", np.sum(a, axis=0)) 
print("Sum:", np.sum(a, axis=1)) 

Sum: [ 9 12]
Sum: [ 3  7 11]


## Fill

### zeros

In [185]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### ones

In [186]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### eye

In [190]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Full

In [187]:
m1 = np.full((5), 3)
m2 = np.full((3, 4), 1)
m3 = np.full((3, 4), 2)
print(m1)
print(m2)
print(m3)

[3 3 3 3 3]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


### Arange

In [188]:
a = np.arange(5)
print(a)
a = np.arange(1, 5)
print(a)
a = np.arange(0, 10, 2)
print(a)

[0 1 2 3 4]
[1 2 3 4]
[0 2 4 6 8]


### Linspace

In [189]:
a = np.linspace(1, 15, 5)
print(a)
len(a)

[ 1.   4.5  8.  11.5 15. ]


5

### Random

#### rand

In [405]:
np.random.rand(5)

array([0.08945811, 0.9871212 , 0.59376162, 0.23135741, 0.91579984])

In [406]:
np.random.rand(3, 5)

array([[0.26138852, 0.47019785, 0.0450763 , 0.28942063, 0.08967719],
       [0.36053047, 0.81420212, 0.10595459, 0.28640034, 0.11302902],
       [0.44616221, 0.8358232 , 0.34750645, 0.49743743, 0.83003129]])

#### random

In [407]:
np.random.random(5)

array([0.46357848, 0.68864876, 0.06689023, 0.19858741, 0.06599861])

In [408]:
np.random.random((3,5))

array([[0.57580035, 0.25032785, 0.08569703, 0.77820282, 0.35526316],
       [0.6291194 , 0.08996146, 0.07056613, 0.33628603, 0.23648441],
       [0.40577702, 0.23074832, 0.19388978, 0.60199377, 0.55938931]])

#### randint

In [409]:
a = np.random.randint(10)
b = np.random.randint(5, 15)
c = np.random.randint(5, 15, 3)
d = np.random.randint(0, 9, 9).reshape((3,3))
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)

a: 0
b: 9
c: [ 5 13 10]
d: [[4 1 4]
 [4 5 7]
 [3 4 8]]


#### shuffle

In [410]:
a = np.arange(1,22).reshape((7,3))
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [411]:
np.random.shuffle(a)
print(a)

[[ 7  8  9]
 [ 1  2  3]
 [16 17 18]
 [10 11 12]
 [ 4  5  6]
 [13 14 15]
 [19 20 21]]


#### normal

In [412]:
np.random.normal()

-0.377129389311405

In [413]:
np.random.normal(size=5)

array([ 2.19058653, -0.13488569, -0.46975246, -0.14268503, -2.25877621])

#### uniform

In [414]:
np.random.uniform()

0.2928716187063376

In [415]:
np.random.uniform(size=5)

array([0.15389768, 0.18587143, 0.49070584, 0.88434281, 0.08788924])

#### choice

In [416]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [417]:
print(np.random.choice(a))

7


In [418]:
print(np.random.choice(a, size=2))

[1 2]


In [419]:
print(np.random.choice(a, size=(3, 3)))

[[5 6 5]
 [6 9 7]
 [9 3 3]]


## Where

In [ ]:
a = np.array(
    [
      [ 1,  2,  3,  4, 5],
      [ 6,  7,  8,  9, 10],
      [ 11, 12, 13, 14, 15]
    ]
)

In [ ]:
print(np.sum(a>14))

1


In [ ]:
np.where(a>14, 1, 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
r = m1*m2
print(r)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [ ]:
r = m1 @ m2.T  # Transpose m2
print(r)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [ ]:
r = m1.dot(m2.T)  # Transpose m2
print(r)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


## File

### Save & Load : Single

In [216]:
#---Save
a = np.zeros((4, 3))
np.save('my_array.npy', a)

#---Load
input = np.load('my_array.npy')
print(input)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Save & Load : Multiple

In [217]:
#---Save
a = np.zeros((4, 3))
b = np.ones((4, 3))
np.savez('my_arrays.npz', a, b)

#---Multiple
input = np.load('my_arrays.npz')
a = input["arr_0"]
b = input["arr_1"]
print(a)
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Math

In [387]:
a = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)
b = np.array(
    [
        [5, 6],
        [7, 8]
    ]
)

### Action

In [261]:
print(a + b)

[[ 6  8]
 [10 12]]


In [262]:
print(a - b)

[[-4 -4]
 [-4 -4]]


In [234]:
print(a * b)

[[ 5 12]
 [21 32]]


In [263]:
print(a / b)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [300]:
print(a == b)

[[False False]
 [False False]]


In [301]:
print(np.array_equal(a, b))

False


### Methods

In [276]:
print(np.subtract(a, b))

[[-4 -4]
 [-4 -4]]


In [277]:
print(np.add(a, b)) 

[[ 6  8]
 [10 12]]


In [278]:
print(np.divide(a, b)) 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [281]:
print(np.exp(a))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [282]:
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [283]:
print(np.sin(a))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


In [284]:
print(np.cos(a))

[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]


In [285]:
print(np.tan(a))

[[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]


In [286]:
print(np.log(a))

[[0.         0.69314718]
 [1.09861229 1.38629436]]


In [289]:
print(np.multiply(a, b))

[[ 5 12]
 [21 32]]


### Matrix Multiplication

In [298]:
print(np.matmul(a, b))
print(a@b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Methods

### Reshape

In [425]:
a = np.array(
    [ 1,  2,  3,  4, 5, 6, 7, 8, 9, 10]
)

In [426]:
b = a.reshape(5,2)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [427]:
b = a.reshape(-1,2)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [428]:
b = a.reshape(2,-1)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [429]:
b = a.reshape(1,-1)
print(b)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [431]:
b = a.reshape(-1,1)
print(b)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


### Concat

In [433]:
a = np.array(
    [ 1,  2,  3,  4]
)
b = np.array(
    [ 5, 6, 7, 8]
)
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6 7 8]


In [ ]:
a = np.array(
    [
        [1, 2],
        [3, 4],
    ]
)
b = np.array(
    [
        [5, 6],
        [7, 8],
    ]
)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [436]:
c = np.concatenate((a, b), axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [438]:
c = np.vstack((a, b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [439]:
c = np.concatenate((a, b), axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [440]:
c = np.hstack((a, b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


### Copy

In [329]:
a = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

b = np.copy(a)
print(b)

b[0] = 10 
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[10 10]
 [ 3  4]]


### Sort

In [343]:
a = np.array([1, 7, 2, 6, 5, 3])
print("Array :\n{}".format(a))
print("lower_sort :\n{}".format(np.sort(a))) 
print("upper_sort  :\n{}".format(np.sort(a)[::-1]))

Array :
[1 7 2 6 5 3]
lower_sort :
[1 2 3 5 6 7]
upper_sort  :
[7 6 5 3 2 1]


In [351]:
a = np.array(
    [
        [1, 7, 2, 6, 5, 3],
        [2, 3, 1, 4, 9, 8 ]
    ]
)
print("Array :\n{}".format(a))
print("column_sort :\n{}".format(np.sort(a, axis=0))) 
print("row_sort :\n{}".format(np.sort(a, axis=1))) 

Array :
[[1 7 2 6 5 3]
 [2 3 1 4 9 8]]
column_sort :
[[1 3 1 4 5 3]
 [2 7 2 6 9 8]]
row_sort :
[[1 2 3 5 6 7]
 [1 2 3 4 8 9]]


### Reverse

In [394]:
a = np.array([1, 7, 2, 6, 5, 3])
b = a[::-1]
print(b)

[3 5 6 2 7 1]


In [398]:
a = np.array(
    [
        [1, 7, 2, 6, 5, 6],
        [2, 3, 1, 4, 9, 7 ],
        [3, 3, 1, 4, 9, 8 ]
    ]
)
print("Array :\n{}".format(a))
print("Reverse :\n{}".format(a[::-1]))

Array :
[[1 7 2 6 5 6]
 [2 3 1 4 9 7]
 [3 3 1 4 9 8]]
Reverse :
[[3 3 1 4 9 8]
 [2 3 1 4 9 7]
 [1 7 2 6 5 6]]


### Transpose

In [401]:
a = np.array(
    [
        [1, 7, 2, 6, 5, 6],
        [2, 3, 1, 4, 9, 7 ],
        [3, 3, 1, 4, 9, 8 ]
    ]
)
print("Array :\n{}".format(a))
print("Transpose :\n{}".format(np.transpose(a)))
print("Transpose :\n{}".format(a.T))

Array :
[[1 7 2 6 5 6]
 [2 3 1 4 9 7]
 [3 3 1 4 9 8]]
Transpose :
[[1 2 3]
 [7 3 3]
 [2 1 1]
 [6 4 4]
 [5 9 9]
 [6 7 8]]
Transpose :
[[1 2 3]
 [7 3 3]
 [2 1 1]
 [6 4 4]
 [5 9 9]
 [6 7 8]]
